export declare const DescBienes: {
    "Animales vivos": string;
    "Productos para animales dom\u00E9sticos": string;
    "Comida de animales": string;
    "Recipientes y h\u00E1bitat para animales": string;
    "Productos de talabarter\u00EDa y arreo": string;
    "Semillas, bulbos, pl\u00E1ntulas y esquejes": string;
    "Productos de floricultura y silvicultura": string;
    "Fertilizantes y nutrientes para plantas y herbicidas": string;
    "Productos para el control de plagas": string;
    "Rosales vivos": string;
    "Plantas vivas de especies o variedades de flores altas": string;
    "Plantas vivas de especies o variedades de flores bajas": string;
    "Crisantemos vivos": string;
    "Claveles vivos": string;
    "Orqu\u00EDdeas vivas": string;
    "Rosas frescas cortadas": string;
    "Bouquets cortados frescos de especies o variedades de flores altas": string;
    "Bouquets cortados frescos de especies o variedades de flores bajas": string;
    "Crisantemos cortados frescos": string;
    "Bouquets florales cortados frescos": string;
    "Claveles cortados frescos": string;
    "Orqu\u00EDdeas cortadas frescas": string;
    "Rosas cortadas secas": string;
    "Bouquets cortados secos de especies o variedades de flores altas": string;
    "Bouquets cortados secos de especies o variedades de flores bajas": string;
    "Crisantemos cortados secos": string;
    "Claveles cortados secos": string;
    "Orqu\u00EDdeas cortadas secas": string;
    "Follaje cortado fresco": string;
    "Minerales, minerales met\u00E1licos y metales": string;
    "Tierra y piedra": string;
    "Productos no comestibles de planta y silvicultura": string;
    "Productos animales no comestibles": string;
    "Chatarra y materiales de desecho": string;
    "Fibra, hilos e hilados": string;
    "Tejidos y materiales de cuero": string;
    Aleaciones: string;
    "\u00D3xido met\u00E1lico": string;
    "Desechos met\u00E1licos y chatarra": string;
    "Materiales explosivos": string;
    "Elementos y gases": string;
    Aditivos: string;
    Colorantes: string;
    "Ceras y aceites": string;
    Solventes: string;
    "Compuestos y mezclas": string;
    "Caucho y elast\u00F3meros": string;
    "Resinas y colofonias y otros materiales derivados de resina": string;
    "Materiales de papel": string;
    "Productos de papel": string;
    "Papel para uso industrial": string;
    Combustibles: string;
    "Combustibles gaseosos y aditivos": string;
    "Lubricantes, aceites, grasas y anticorrosivos": string;
    "Combustible para reactores nucleares": string;
    "Maquinaria y equipo de miner\u00EDa y explotaci\u00F3n de canteras": string;
    "Equipo de perforaci\u00F3n y explotaci\u00F3n de pozos": string;
    "Equipo para perforaci\u00F3n y exploraci\u00F3n de petr\u00F3leo y gas": string;
    "Materiales para perforaci\u00F3n y operaciones de petr\u00F3leo y gas": string;
    "Equipo de producci\u00F3n y operaci\u00F3n de petr\u00F3leo y gas": string;
    "Maquinaria y equipo para agricultura, silvicultura y paisajismo": string;
    "Equipo de pesca y acuicultura": string;
    "Maquinaria y equipo pesado de construcci\u00F3n": string;
    "Maquinaria para el procesamiento de materias primas": string;
    "Maquinaria para el procesamiento de petr\u00F3leo": string;
    "Maquinaria y accesorios de textiles y tejidos": string;
    "Maquinaria y equipos lapidarios": string;
    "Maquinaria de reparaci\u00F3n y accesorios para marroquiner\u00EDa": string;
    "Maquinaria, equipo y suministros de procesos industriales": string;
    "M\u00E1quinas, equipo y suministros para fundici\u00F3n": string;
    "Equipo industrial para alimentos y bebidas": string;
    "Mezcladores y sus partes y accesorios": string;
    "Equipamiento para transferencia de masa": string;
    "Maquinaria de fabricaci\u00F3n electr\u00F3nica, equipo y accesorios": string;
    "Equipo y maquinaria de procesamiento de pollos": string;
    "Equipo y maquinaria de procesamiento de madera y aserrado": string;
    "Maquinaria y accesorios para cortar metales": string;
    "Maquinaria y accesorios para el formado de metales": string;
    "Maquinaria y accesorios para hacer prototipos r\u00E1pidos": string;
    "Maquinaria y accesorios y suministros para soldadura de todas las clases": string;
    "Maquinaria para el tratamiento de metal": string;
    "Herramientas de maquinado industrial": string;
    "Maquinaria y equipo para cable": string;
    "Maquinaria y equipo para manejo de materiales": string;
    "Recipientes y almacenamiento": string;
    "Materiales de empaque": string;
    "Refrigeraci\u00F3n industrial": string;
    "Suministros de embalaje": string;
    "Veh\u00EDculos de motor": string;
    "Transporte mar\u00EDtimo": string;
    "Maquinaria y equipo para ferrocarril y tranv\u00EDas": string;
    Aeronaves: string;
    "Naves espaciales": string;
    "Bicicletas no motorizadas": string;
    "Componentes y sistemas de transporte": string;
    "Carrocer\u00EDas y remolques": string;
    "Equipo para servicios de transporte": string;
    "Sistemas y componentes y equipos aeroespaciales": string;
    "Fuentes de energ\u00EDa": string;
    "Bater\u00EDas y generadores y transmisi\u00F3n de energ\u00EDa cin\u00E9tica": string;
    "Alambres, cables y arneses": string;
    "Generaci\u00F3n de energ\u00EDa": string;
    "Maquinaria y equipo para energ\u00EDa at\u00F3mica o nuclear": string;
    "Herramientas de mano": string;
    "Maquinaria y equipo hidr\u00E1ulico": string;
    "Maquinaria y equipo neum\u00E1tico": string;
    "Herramientas especializadas automotrices": string;
    "Componentes estructurales y formas b\u00E1sicas": string;
    "Hormig\u00F3n, cemento y yeso": string;
    "Carreteras y paisaje": string;
    "Productos de construcci\u00F3n estructurales": string;
    Aislamiento: string;
    "Materiales para acabado de exteriores": string;
    "Materiales de acabado de interiores": string;
    "Puertas y ventanas y vidrio": string;
    "Instalaciones de plomer\u00EDa": string;
    "Equipo de apoyo para Construcci\u00F3n y Mantenimiento": string;
    "Componentes de construcci\u00F3n de estructura port\u00E1til": string;
    "Estructuras y materiales de miner\u00EDa subterr\u00E1nea": string;
    "Materiales estructurales": string;
    "Componentes y Suministros de Manufactura": string;
    "Piezas de fundici\u00F3n y ensambles de piezas de fundici\u00F3n": string;
    Extrusiones: string;
    "Piezas fundidas maquinadas": string;
    Forjaduras: string;
    Molduras: string;
    "Cuerda, cadena, cable, alambre y correa": string;
    Ferretería: string;
    "Rodamientos, cojinetes ruedas y engranajes": string;
    "Empaques, gl\u00E1ndulas, fundas y cubiertas": string;
    "Materiales de afilado pulido y alisado": string;
    "Adhesivos y selladores": string;
    "Pinturas y bases y acabados": string;
    "Extractos de te\u00F1ir y de curtir": string;
    "Materia prima en placas o barras labradas": string;
    "\u00D3ptica industrial": string;
    "Sistemas de control neum\u00E1tico, hidr\u00E1ulico o el\u00E9ctrico": string;
    "Cubiertas, cajas y envolturas": string;
    "Piezas hechas a m\u00E1quina": string;
    "Componentes de placa y estampados": string;
    "Extrusiones maquinadas": string;
    "Forjas labradas": string;
    "Ensambles de tuber\u00EDa fabricada": string;
    "Ensambles fabricados de material en barras": string;
    "Ensambles estructurales fabricados": string;
    "Ensambles de l\u00E1mina fabricado": string;
    "Ensambles de placa fabricados": string;
    Refractarios: string;
    "Imanes y materiales magn\u00E9ticos": string;
    Maquinados: string;
    Empaques: string;
    Sellos: string;
    "Partes sinterizadas": string;
    "Circuitos impresos, circuitos integrados y micro ensamblajes": string;
    "Dispositivo semiconductor discreto": string;
    "Componentes pasivos discretos": string;
    "Piezas de componentes y hardware electr\u00F3nicos y accesorios": string;
    "Dispositivos de tubo electr\u00F3nico y accesorios": string;
    "Dispositivos y componentes y accesorios de control de automatizaci\u00F3n": string;
    "L\u00E1mparas y bombillas y componentes para l\u00E1mparas": string;
    "Iluminaci\u00F3n, artefactos y accesorios": string;
    "Equipos, suministros y componentes el\u00E9ctricos": string;
    "Dispositivos y accesorios y suministros de manejo de cable el\u00E9ctrico": string;
    "Calefacci\u00F3n, ventilaci\u00F3n y circulaci\u00F3n del aire": string;
    "Distribuci\u00F3n de fluidos y gas": string;
    "Bombas y compresores industriales": string;
    "Filtrado y purificaci\u00F3n industrial": string;
    "Instalaciones de tubos y entubamientos": string;
    "Instalaciones de tubos y tuber\u00EDas": string;
    "Equipo de laboratorio y cient\u00EDfico": string;
    "Instrumentos de medida, observaci\u00F3n y ensayo": string;
    "Suministros y accesorios de laboratorio": string;
    "Equipos y suministros veterinarios": string;
    "Telas y vestidos m\u00E9dicos": string;
    "Suministros, productos de tratamiento y cuidado del enfermo": string;
    "Equipos y suministros dentales": string;
    "Equipo de di\u00E1lisis y suministros": string;
    "Productos para los servicios m\u00E9dicos de urgencias y campo": string;
    "Productos de examen y control del paciente": string;
    "Productos de centro m\u00E9dico": string;
    "Productos de hacer im\u00E1genes diagn\u00F3sticas m\u00E9dicas y de medicina nuclear": string;
    "Ayuda para personas con desaf\u00EDos f\u00EDsicos para vivir independiente": string;
    "Productos para administraci\u00F3n intravenosa y arterial": string;
    "Nutrici\u00F3n cl\u00EDnica": string;
    "Productos medicinales de deportes y ortop\u00E9dicos y pr\u00F3tesis": string;
    "Productos de rehabilitaci\u00F3n y terapia ocupacional y f\u00EDsica": string;
    "Equipo y suministros post mortem y funerarios": string;
    "Productos de resucitaci\u00F3n, anestesia y respiratorio": string;
    "Productos para la esterilizaci\u00F3n m\u00E9dica": string;
    "Productos quir\u00FArgicos": string;
    "Suministros para formaci\u00F3n y estudios de medicina": string;
    "Productos para el cuidado de heridas": string;
    "Implantes ortop\u00E9dicos quir\u00FArgicos": string;
    "Dispositivos de comunicaciones y accesorios": string;
    "Componentes para tecnolog\u00EDa de la informaci\u00F3n, difusi\u00F3n o telecomunicaciones": string;
    "Equipo inform\u00E1tico y accesorios": string;
    "Equipos o plataformas y accesorios de redes multimedia o de voz y datos": string;
    Software: string;
    "Maquinaria, suministros y accesorios de oficina": string;
    "Accesorios de oficina y escritorio": string;
    "Suministros de oficina": string;
    "Equipo de imprenta y publicaci\u00F3n": string;
    "Equipos de audio y video para presentaci\u00F3n y composici\u00F3n": string;
    "Equipo de v\u00EDdeo, filmaci\u00F3n o fotograf\u00EDa": string;
    "Medios fotogr\u00E1ficos y de grabaci\u00F3n": string;
    "Suministros fotogr\u00E1ficos para cine": string;
    "Armas ligeras y munici\u00F3n": string;
    "Armas de guerra convencionales": string;
    Misiles: string;
    "Cohetes y subsistemas": string;
    Lanzadores: string;
    "Protecci\u00F3n del Orden P\u00FAblico": string;
    "Seguridad y control p\u00FAblico": string;
    "Seguridad, vigilancia y detecci\u00F3n": string;
    "Seguridad y protecci\u00F3n personal": string;
    "Protecci\u00F3n contra incendios": string;
    "Equipo de entrenamiento de seguridad f\u00EDsica e industrial, defensa y orden p\u00FAblico": string;
    "Tratamiento, suministros y eliminaci\u00F3n de agua y aguas residuales": string;
    "Equipo industrial de lavander\u00EDa y lavado en seco": string;
    "Equipo de aseo": string;
    "Suministros de aseo y limpieza": string;
    "Equipos de servicios de alimentaci\u00F3n para instituciones": string;
    "M\u00E1quinas expendedoras": string;
    "Equipo de Juego o de Apostar": string;
    "Equipo y materiales funerarios": string;
    "Coleccionables y condecoraciones": string;
    "Equipos y accesorios para acampada y exteriores": string;
    "Equipos de pesca y caza": string;
    "Equipos para deportes acu\u00E1ticos": string;
    "Equipos para deportes de invierno": string;
    "Equipos deportivos para campos y canchas": string;
    "Equipos de gimnasia y boxeo": string;
    "Juegos, equipo de tiro y mesa": string;
    "Equipo para entrenamiento f\u00EDsico": string;
    "Otros deportes": string;
    "Equipo y accesorios para deportes": string;
    "Equipo de recreo, parques infantiles y equipo y suministros de nataci\u00F3n y de spa": string;
    "Frutos secos": string;
    "Productos de carne y aves de corral": string;
    "Pescados y mariscos": string;
    "Productos l\u00E1cteos y huevos": string;
    "Aceites y grasas comestibles": string;
    "Chocolates, az\u00FAcares, edulcorantes y productos de confiter\u00EDa": string;
    "Condimentos y conservantes": string;
    "Productos de panader\u00EDa": string;
    "Alimentos preparados y conservados": string;
    Bebidas: string;
    "Tabaco y productos de fumar y substitutos": string;
    "Productos de cereales y legumbres": string;
    "Fruta fresca": string;
    "Fruta org\u00E1nica fresca": string;
    "Fruta seca": string;
    "Fruta org\u00E1nica seca": string;
    "Fruta congelada": string;
    "Fruta org\u00E1nica congelada": string;
    "Fruta en lata o en frasco": string;
    "Fruta org\u00E1nica en lata o en frasco": string;
    "Pur\u00E9 de frutas": string;
    "Vegetales frescos": string;
    "Vegetales org\u00E1nicos frescos": string;
    "Vegetales secos": string;
    "Vegetales org\u00E1nicos secos": string;
    "Vegetales congelados": string;
    "Vegetales org\u00E1nicos congelados": string;
    "Vegetales en lata o en frasco": string;
    "Vegetales org\u00E1nicos en lata o en frasco": string;
    "Medicamentos antiinfecciosos": string;
    "Agentes antitumorales": string;
    "Medicamentos cardiovasculares": string;
    "Medicamentos hemat\u00F3logos": string;
    "Medicamentos para el sistema nervioso central": string;
    "Medicamentos para el sistema nervioso aut\u00F3nomo": string;
    "Medicamentos que afectan al sistema respiratorio": string;
    "Medicamentos que afectan al sistema gastrointestinal": string;
    "Hormonas y antagonistas hormonales": string;
    "Agentes que afectan el agua y los electrolitos": string;
    "Medicamentos inmunomoduladores": string;
    "Categor\u00EDas de medicamentos varios": string;
    "F\u00E1rmacos que afectan a los o\u00EDdos, los ojos, la nariz y la piel": string;
    "Suplementos alimenticios veterinarios": string;
    "Revestimientos de suelos": string;
    "Ropa de cama, manteler\u00EDas, pa\u00F1os de cocina y toallas": string;
    "Tratamientos de ventanas": string;
    "Aparatos electrodom\u00E9sticos": string;
    "Utensilios de cocina dom\u00E9sticos": string;
    "Electr\u00F3nica de consumo": string;
    "Tratamientos de pared dom\u00E9stica": string;
    Ropa: string;
    Calzado: string;
    "Maletas, bolsos de mano, mochilas y estuches": string;
    "Art\u00EDculos de tocador y cuidado personal": string;
    "Fuentes y accesorios de costura": string;
    Joyería: string;
    Relojes: string;
    Gemas: string;
    "Medios impresos": string;
    "Material electr\u00F3nico de referencia": string;
    "Etiquetado y accesorios": string;
    "Muebles de alojamiento": string;
    "Muebles comerciales e industriales": string;
    "Mobiliario institucional, escolar y educativo y accesorios": string;
    "Muebles y accesorios para merchandising": string;
    "Adornos para el hogar": string;
    "Materiales did\u00E1cticos profesionales y de desarrollo y accesorios y suministros": string;
    "Decoraciones y suministros del aula": string;
    "Equipo, accesorios y suministros de arte y manualidades": string;
    "Instrumentos musicales, piezas y accesorios": string;
    "Juguetes y juegos": string;
    "Pesquer\u00EDas y acuicultura": string;
    Horticultura: string;
    "Servicios de animales vivos": string;
    "Preparaci\u00F3n, gesti\u00F3n y protecci\u00F3n del terreno y del suelo": string;
    "Producci\u00F3n, gesti\u00F3n y protecci\u00F3n de cultivos": string;
    Silvicultura: string;
    "Fauna y flora silvestres": string;
    "Desarrollo y vigilancia de recursos hidr\u00E1ulicos": string;
    "Servicios de miner\u00EDa": string;
    "Servicios de perforaci\u00F3n y prospecci\u00F3n petrol\u00EDfera y de gas": string;
    "Servicios de construcci\u00F3n y perforaci\u00F3n de pozos": string;
    "Servicios de aumento de la extracci\u00F3n y producci\u00F3n de gas y petr\u00F3leo": string;
    "Servicios de restauraci\u00F3n y recuperaci\u00F3n de gas y petr\u00F3leo": string;
    "Servicios de procesamiento y gesti\u00F3n de datos de petr\u00F3leo y gas": string;
    "Servicios de gerencia de proyectos en pozos de petr\u00F3leo y gas": string;
    "Servicios de mantenimiento y reparaciones de construcciones e instalaciones": string;
    "Servicios de construcci\u00F3n de edificaciones residenciales": string;
    "Servicios de construcci\u00F3n de edificaciones no residenciales": string;
    "Servicios de construcci\u00F3n pesada": string;
    "Servicios de mantenimiento y construcci\u00F3n de comercio especializado": string;
    "Industrias de pl\u00E1sticos y productos qu\u00EDmicos": string;
    "Industrias de la madera y el papel": string;
    "Industrias del metal y de minerales": string;
    "Industrias de alimentos y bebidas": string;
    "Industrias de fibras, textiles y de tejidos": string;
    "Servicios de apoyo a la fabricaci\u00F3n": string;
    "Fabricaci\u00F3n de maquinaria y equipo de transporte": string;
    "Fabricaci\u00F3n de productos el\u00E9ctricos e instrumentos de precisi\u00F3n": string;
    "Servicios de maquinado y procesado": string;
    "Servicios de descontaminaci\u00F3n": string;
    "Servicios de aseo y limpieza": string;
    "Eliminaci\u00F3n y tratamiento de desechos": string;
    "Limpieza de residuos t\u00F3xicos y peligrosos": string;
    "Gesti\u00F3n medioambiental": string;
    "Protecci\u00F3n medioambiental": string;
    "Seguimiento, control y rehabilitaci\u00F3n de la contaminaci\u00F3n": string;
    "Servicios de seguimiento, control o rehabilitaci\u00F3n de contaminantes": string;
    "Transporte de correo y carga": string;
    "Transporte de pasajeros": string;
    "Manejo y embalaje de material": string;
    Almacenaje: string;
    "Servicios de transporte": string;
    "Servicios de mantenimiento o reparaciones de transportes": string;
    "Servicios de asesor\u00EDa de gesti\u00F3n": string;
    "Servicios de recursos humanos": string;
    "Servicios legales": string;
    "Servicios inmobiliarios": string;
    "Comercializaci\u00F3n y distribuci\u00F3n": string;
    "Pol\u00EDtica comercial y servicios": string;
    "Servicios de administraci\u00F3n de empresas": string;
    "Servicios profesionales de ingenier\u00EDa": string;
    "Servicios inform\u00E1ticos": string;
    Economía: string;
    Estadística: string;
    "Tecnolog\u00EDas de fabricaci\u00F3n": string;
    "Servicios de pedolog\u00EDa": string;
    "Entrega de servicios de tecnolog\u00EDa de informaci\u00F3n": string;
    Publicidad: string;
    "Escritura y traducciones": string;
    "Servicios de reproducci\u00F3n": string;
    "Servicios fotogr\u00E1ficos": string;
    "Dise\u00F1o gr\u00E1fico": string;
    "Artistas e int\u00E9rpretes profesionales": string;
    "Servicios p\u00FAblicos": string;
    "Servicios de medios de telecomunicaciones": string;
    "Servicios de informaci\u00F3n": string;
    "Finanzas de desarrollo": string;
    "Servicios de contabilidad y auditorias": string;
    "Banca e inversiones": string;
    "Servicios de seguros y pensiones": string;
    "Agencias de cr\u00E9dito": string;
    "Servicios integrales de salud": string;
    "Prevenci\u00F3n y control de enfermedades": string;
    "Pr\u00E1ctica m\u00E9dica": string;
    "Ciencia m\u00E9dica, investigaci\u00F3n y experimentaci\u00F3n": string;
    "Medicina alternativa y hol\u00EDstica": string;
    "Servicios alimenticios y de nutrici\u00F3n": string;
    "Servicios de mantenimiento, renovaci\u00F3n y reparaci\u00F3n de equipo m\u00E9dico quir\u00FArgico": string;
    "Servicios de muerte y soporte al fallecimiento": string;
    "Formaci\u00F3n profesional": string;
    "Sistemas educativos alternativos": string;
    "Instituciones educativas": string;
    "Servicios educativos especializados": string;
    "Instalaciones educativas": string;
    "Restaurantes y catering (servicios de comidas y bebidas)": string;
    "Instalaciones hoteleras, alojamientos y centros de encuentros": string;
    "Facilitaci\u00F3n de viajes": string;
    "Artes interpretativas": string;
    "Deportes comerciales": string;
    "Servicios de entretenimiento": string;
    "Aspecto personal": string;
    "Asistencia dom\u00E9stica y personal": string;
    "Orden p\u00FAblico y seguridad": string;
    "Servicios militares o defensa nacional": string;
    "Sistemas e instituciones pol\u00EDticas": string;
    "Condiciones sociopol\u00EDticas": string;
    "Relaciones internacionales": string;
    "Ayuda y asistencia humanitaria": string;
    "Servicios comunitarios y sociales": string;
    "Servicios de administraci\u00F3n y financiaci\u00F3n p\u00FAblica": string;
    Tributación: string;
    "Pol\u00EDtica y regulaci\u00F3n comercial": string;
    "Organizaciones laborales": string;
    "Organizaciones religiosas": string;
    Clubes: string;
    "Organizaciones, asociaciones y movimientos c\u00EDvicos": string;
    "Parcelas de tierra": string;
    Vías: string;
    "Estructuras y edificios permanentes": string;
    "Estructuras y edificios m\u00F3viles": string;
    "Estructuras y edificios prefabricados": string;
};
