export declare const Paises: {
    CHILE: string;
    "ISLAS COCOS": string;
    "REPUBLICA DE CONGO": string;
    "COREA DEL SUR": string;
    CROACIA: string;
    DINAMARCA: string;
    "REPUBLICA DOMINICANA": string;
    "EMIRATOS ARABES UNIDOS": string;
    ESLOVENIA: string;
    ETIOPIA: string;
    FINLANDIA: string;
    "ESTADOS UNIDOS": string;
    GABON: string;
    GEORGIA: string;
    GIBRALTAR: string;
    GROENLANDIA: string;
    GUATEMALA: string;
    GUINEA: string;
    "GUINEA BISAU": string;
    "ISLAS HEARD Y MCDONALD": string;
    INDIA: string;
    IRAK: string;
    ISLANDIA: string;
    JAMAICA: string;
    JORDANIA: string;
    KIRGUISTAN: string;
    KUWAIT: string;
    LETONIA: string;
    LIBIA: string;
    LITUANIA: string;
    "REPUBLICA DE MACEDONIA": string;
    MALDIVAS: string;
    "ISLAS MALVINAS": string;
    MARRUECOS: string;
    MAURICIO: string;
    MAYOTTE: string;
    MOLDAVIA: string;
    MONTENEGRO: string;
    NAMIBIA: string;
    "ISLA DE NAVIDAD": string;
    AFGANISTAN: string;
    ALANDE: string;
    ALBANIA: string;
    ALEMANIA: string;
    ANDORRA: string;
    ANGOLA: string;
    ANGUILA: string;
    "ANTIGUA Y BARBUDA": string;
    "ANTILLAS NEERLANDESAS": string;
    "ARABIA SAUDITA": string;
    ALGELIA: string;
    ARMENIA: string;
    ARUBA: string;
    AUSTRALIA: string;
    AUSTRIA: string;
    AZERBAIYAN: string;
    BAHAMAS: string;
    BAREIN: string;
    BANGLADES: string;
    BARBADOS: string;
    BELGICA: string;
    BELICE: string;
    BENIN: string;
    BERMUDAS: string;
    BIELORRUSIA: string;
    BIRMANIA: string;
    BOLIVIA: string;
    "BOSNIA AND HERZEGOVINA": string;
    BOTSUANA: string;
    "ISLA BOUVET": string;
    BRASIL: string;
    BRUNEI: string;
    BULGARIA: string;
    "BURKINA FASO": string;
    BURUNDI: string;
    BUTAN: string;
    "CABO VERDE": string;
    "ISLAS CAIMAN": string;
    CAMBOYA: string;
    CAMERUN: string;
    CANADA: string;
    "REPUBLICA CENTROAFRICANA": string;
    CHAD: string;
    "REPUBLICA CHECA": string;
    CHINA: string;
    CHIPRE: string;
    COMORAS: string;
    "REPUBLICA DEMOCRATICA DEL CONGO": string;
    "ISLAS COOK": string;
    "COREA DEL NORTE": string;
    "COSTA DE MARFIL": string;
    "COSTA RICA": string;
    CURAZAO: string;
    CUBA: string;
    DOMINICA: string;
    ECUADOR: string;
    EGIPTO: string;
    "EL SALVADOR": string;
    ERITREA: string;
    ESLOVAQUIA: string;
    ESPAÑA: string;
    ESTONIA: string;
    "ISLAS FEROE": string;
    FILIPINAS: string;
    FIYI: string;
    FRANCIA: string;
    GAMBIA: string;
    "ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR": string;
    GHANA: string;
    GRANADA: string;
    GRECIA: string;
    GUADALUPE: string;
    GUAM: string;
    "GUAYANA FRANCESA": string;
    GUERNSEY: string;
    "GUINEA ECUATORIAL": string;
    GUYANA: string;
    HAITI: string;
    HONDURAS: string;
    "HONG KONG": string;
    HUNGRIA: string;
    INDONESIA: string;
    IRAN: string;
    IRLANDA: string;
    ISRAEL: string;
    ITALIA: string;
    JAPON: string;
    JERSEY: string;
    KAZAJISTAN: string;
    KENIA: string;
    KIRIBATI: string;
    LAOS: string;
    LESOTO: string;
    LIBANO: string;
    LIBERIA: string;
    LIECHTENSTEIN: string;
    LUXEMBURGO: string;
    MACAO: string;
    MADAGASCAR: string;
    MALASIA: string;
    MALAUI: string;
    MALI: string;
    MALTA: string;
    "ISLA DE MAN": string;
    "ISLAS MARIANAS DEL NORTE": string;
    "ISLAS MARSHALL": string;
    MARTINICA: string;
    MAURITANIA: string;
    MEXICO: string;
    MICRONESIA: string;
    MONACO: string;
    MONGOLIA: string;
    MONTSERRAT: string;
    MOZAMBIQUE: string;
    NAURU: string;
    NEPAL: string;
    COLOMBIA: string;
    NICARAGUA: string;
    NIGER: string;
    NIGERIA: string;
    NIUE: string;
    NORFOLK: string;
    NORUEGA: string;
    "NUEVA CALEDONIA": string;
    "NUEVA ZELANDA": string;
    OMAN: string;
    "PAISES BAJOS": string;
    PAKISTAN: string;
    PALAOS: string;
    "ESTADO DE PALESTINA": string;
    PANAMA: string;
    "PAPUA NUEVA GUINEA": string;
    PARAGUAY: string;
    PERU: string;
    "ISLAS PITCAIRN": string;
    "POLINESIA FRANCESA": string;
    POLONIA: string;
    PORTUGAL: string;
    "PUERTO RICO": string;
    CATAR: string;
    "REINO UNIDO": string;
    REUNION: string;
    RUANDA: string;
    RUMANIA: string;
    RUSIA: string;
    "SAHARA OCCIDENTAL": string;
    "ISLAS SALOMON": string;
    SAMOA: string;
    "SAMOA AMERICANA": string;
    "SAN BARTOLOME": string;
    "SAN CRISTOBAL Y NIEVES": string;
    "SAN MARINO": string;
    "SAN MARTIN": string;
    "SAN PEDRO Y MIQUELON": string;
    "SAN VICENTE Y LAS GRANADINAS": string;
    "SANTA HELENA": string;
    "SANTA LUCIA": string;
    "SANTO TOME Y PRINCIPE": string;
    SENEGAL: string;
    SERBIA: string;
    SEYCHELLES: string;
    "SIERRA LEONA": string;
    SINGAPUR: string;
    SIRIA: string;
    SOMALIA: string;
    "SRI LANKA": string;
    SUAZILANDIA: string;
    SUDAFRICA: string;
    SUDAN: string;
    "SUDAN DEL SUR": string;
    SUECIA: string;
    SUIZA: string;
    SURINAM: string;
    "SVALBARD Y JAN MAYEN": string;
    TAILANDIA: string;
    TAIWAN: string;
    TANZANIA: string;
    TAYIKISTAN: string;
    "TERRITORIO BRITANICO DEL OCEANO INDICO": string;
    "TERRITORIOS AUSTRALES FRANCESES": string;
    "TIMOR ORIENTAL": string;
    TOGO: string;
    TOKELAU: string;
    TONGA: string;
    "TRINIDAD Y TOBAGO": string;
    TUNEZ: string;
    "ISLAS TURCAS Y CAICOS": string;
    TURKMENISTAN: string;
    TURQUIA: string;
    TUVALU: string;
    UCRANIA: string;
    UGANDA: string;
    URUGUAY: string;
    UZBEKISTAN: string;
    VANUATU: string;
    "CIUDAD DEL VATICANO": string;
    VENEZUELA: string;
    VIETNAM: string;
    "ISLAS VIRGENES BRITANICAS": string;
    "ISLAS VIRGENES DE LOS ESTADOS UNIDOS": string;
    "WALLIS Y FUTUNA": string;
    YEMEN: string;
    YIBUTI: string;
    ZAMBIA: string;
    ZIMBABUE: string;
    ARGENTINA: string;
    "NO EXISTE": string;
};
