export declare const CatBienes: {
    "Material Vivo Vegetal y Animal, Accesorios y Suministros": string;
    "Material Mineral, Textil y Vegetal y Animal No Comestible": string;
    "Material Qu\u00EDmico incluyendo Bioqu\u00EDmicos y Materiales de Gas": string;
    "Materiales de Resina, Colofonia, Caucho, Espuma, Pel\u00EDcula y Elast\u00F3mericos": string;
    "Materiales y Productos de Papel": string;
    "Materiales Combustibles, Aditivos para Combustibles, Lubricantes y Anticorrosivos": string;
    "Maquinaria y Accesorios de Miner\u00EDa y Perforaci\u00F3n de Pozos": string;
    "Maquinaria y Accesorios para Agricultura, Pesca, Silvicultura y Fauna": string;
    "Maquinaria y Accesorios para Construcci\u00F3n y Edificaci\u00F3n": string;
    "Maquinaria y Accesorios para Manufactura y Procesamiento Industrial": string;
    "Maquinaria, Accesorios y Suministros para Manejo, Acondicionamiento y Almacenamiento de Materiales": string;
    "Veh\u00EDculos Comerciales, Militares y Particulares, Accesorios y Componentes": string;
    "Maquinaria y Accesorios para Generaci\u00F3n y Distribuci\u00F3n de Energ\u00EDa": string;
    "Herramientas y Maquinaria General": string;
    "Componentes y Suministros para Estructuras, Edificaci\u00F3n, Construcci\u00F3n y Obras Civiles": string;
    "Componentes y Suministros de Manufactura": string;
    "Componentes y Suministros Electr\u00F3nicos": string;
    "Componentes, Accesorios y Suministros de Sistemas El\u00E9ctricos e Iluminaci\u00F3n": string;
    "Componentes y Equipos para Distribuci\u00F3n y Sistemas de Acondicionamiento": string;
    "Equipos y Suministros de Laboratorio, de Medici\u00F3n, de Observaci\u00F3n y de Pruebas": string;
    "Equipo M\u00E9dico, Accesorios y Suministros": string;
    "Difusi\u00F3n de Tecnolog\u00EDas de Informaci\u00F3n y Telecomunicaciones": string;
    "Equipos de Oficina, Accesorios y Suministros": string;
    "Equipos y Suministros para Impresi\u00F3n, Fotografia y Audiovisuales": string;
    "Equipos y Suministros de Defensa, Orden Publico, Proteccion, Vigilancia y Seguridad": string;
    "Equipos de Limpieza y Suministros": string;
    "Maquinaria, Equipo y Suministros para la Industria de Servicios": string;
    "Equipos, Suministros y Accesorios para Deportes y Recreaci\u00F3n": string;
    "Alimentos, Bebidas y Tabaco": string;
    "Medicamentos y Productos Farmac\u00E9uticos": string;
    "Art\u00EDculos Dom\u00E9sticos, Suministros y Productos Electr\u00F3nicos de Consumo": string;
    "Ropa, Maletas y Productos de Aseo Personal": string;
    "Productos para Relojer\u00EDa, Joyer\u00EDa y Piedras Preciosas": string;
    "Publicaciones Impresas, Publicaciones Electr\u00F3nicas y Accesorios": string;
    "Muebles, Mobiliario y Decoraci\u00F3n": string;
    "Instrumentos Musicales, Juegos, Juguetes, Artes, Artesan\u00EDas y Equipo educativo, Materiales, Accesorios y Suministros": string;
    "Servicios de Contratacion Agr\u00EDcola, Pesquera, Forestal y de Fauna": string;
    "Servicios de Miner\u00EDa, Petr\u00F3leo y Gas": string;
    "Servicios de Edificaci\u00F3n, Construcci\u00F3n de Instalaciones y Mantenimiento": string;
    "Servicios de Producci\u00F3n Industrial y Manufactura": string;
    "Servicios de Limpieza, Descontaminaci\u00F3n y Tratamiento de Residuos": string;
    "Servicios Medioambientales": string;
    "Servicios de Transporte, Almacenaje y Correo": string;
    "Servicios de Gesti\u00F3n, Servicios Profesionales de Empresa y Servicios Administrativos": string;
    "Servicios Basados en Ingenier\u00EDa, Investigaci\u00F3n y Tecnolog\u00EDa": string;
    "Servicios Editoriales, de Dise\u00F1o, de Artes Graficas y Bellas Artes": string;
    "Servicios P\u00FAblicos y Servicios Relacionados con el Sector P\u00FAblico": string;
    "Servicios Financieros y de Seguros": string;
    "Servicios de Salud": string;
    "Servicios Educativos y de Formaci\u00F3n": string;
    "Servicios de Viajes, Alimentaci\u00F3n, Alojamiento y Entretenimiento": string;
    "Servicios Personales y Dom\u00E9sticos": string;
    "Servicios de Defensa Nacional, Orden Publico, Seguridad y Vigilancia": string;
    "Servicios Pol\u00EDticos y de Asuntos C\u00EDvicos": string;
    "Organizaciones y Clubes": string;
    "Terrenos, Edificios, Estructuras y V\u00EDas": string;
};
