export declare const Monedas: {
    "Emiratos \u00C1rabes Unidos": string;
    Afganistán: string;
    Albania: string;
    Armenia: string;
    "Curazao, Saint Maarten": string;
    Angola: string;
    Argentina: string;
    "Australia, Isla de Navidad, Islas Cocos, Islas Heard y McDonald, Kiribati, Nauru, Norfolk, Tuvalu": string;
    Aruba: string;
    Azerbaiyán: string;
    "Bosnia y Herzegovina": string;
    Barbados: string;
    Bangladés: string;
    Bulgaria: string;
    Baréin: string;
    Burundi: string;
    Bermudas: string;
    Brunéi: string;
    Bolivia: string;
    Brasil: string;
    Bahamas: string;
    Bután: string;
    Botsuana: string;
    Bielorrusia: string;
    Belice: string;
    Canadá: string;
    "Rep\u00FAblica Democr\u00E1tica del Congo": string;
    "Liechtenstein, Suiza": string;
    Chile: string;
    China: string;
    Colombia: string;
    "Costa Rica": string;
    Cuba: string;
    "Cabo Verde": string;
    "Rep\u00FAblica Checa": string;
    Yibuti: string;
    "Dinamarca, Groenlandia, Islas Feroe": string;
    "Rep\u00FAblica Dominicana": string;
    Argelia: string;
    Egipto: string;
    Eritrea: string;
    Etiopía: string;
    "Alemania, Andorra, Austria, B\u00E9lgica, Chipre, Ciudad del Vaticano, Eslovaquia, Eslovenia, Espa\u00F1a, Estonia, Finlandia, Francia, Grecia, Guadalupe, Guayana Francesa, Irlanda, Italia, Letonia, Lituania, Luxemburgo, Malta, Martinica, Mayotte, M\u00F3naco, Montenegro, Pa\u00EDses Bajos, Portugal, Reuni\u00F3n, San Bartolom\u00E9, San Marino, San Mart\u00EDn, San Pedro y Miquel\u00F3n, Tierras Australes y Ant\u00E1rticas Francesas, Uni\u00F3n Europea": string;
    Fiyi: string;
    "Islas Malvinas": string;
    "Guernsey, Isla de Man, Jersey, Reino Unido": string;
    Georgia: string;
    Ghana: string;
    Gibraltar: string;
    Gambia: string;
    Guinea: string;
    Guatemala: string;
    Guyana: string;
    "Hong Kong": string;
    Honduras: string;
    Croacia: string;
    Haití: string;
    Hungría: string;
    Indonesia: string;
    Israel: string;
    "But\u00E1n, India": string;
    Irak: string;
    Irán: string;
    Islandia: string;
    Jamaica: string;
    Jordania: string;
    Japón: string;
    Kenia: string;
    Kirguistán: string;
    Camboya: string;
    Comoras: string;
    "Corea del Norte": string;
    "Corea del Sur": string;
    Kuwait: string;
    "Islas Caim\u00E1n": string;
    Kazajistán: string;
    Laos: string;
    Líbano: string;
    "Sri Lanka": string;
    Liberia: string;
    Lesoto: string;
    Libia: string;
    "Marruecos, Rep\u00FAblica \u00C1rabe Saharaui Democr\u00E1tica": string;
    Moldavia: string;
    Madagascar: string;
    Macedonia: string;
    Myanmar: string;
    Mongolia: string;
    Macao: string;
    Mauritania: string;
    Mauricio: string;
    Maldivas: string;
    Malaui: string;
    México: string;
    Malasia: string;
    Mozambique: string;
    Namibia: string;
    Nigeria: string;
    Nicaragua: string;
    "Isla Bouvet, Noruega, Svalbard y Jan Mayen": string;
    Nepal: string;
    "Islas Cook, Islas Pitcairn, Niue, Nueva Zelanda, Tokelau": string;
    Omán: string;
    Panamá: string;
    Perú: string;
    "Pap\u00FAa Nueva Guinea": string;
    Filipinas: string;
    Pakistán: string;
    Polonia: string;
    Paraguay: string;
    Catar: string;
    Rumania: string;
    Serbia: string;
    Rusia: string;
    Ruanda: string;
    "Arabia Saudita": string;
    "Islas Salom\u00F3n": string;
    Seychelles: string;
    Sudán: string;
    Suecia: string;
    Singapur: string;
    "Santa Elena, Ascensi\u00F3n y Trist\u00E1n de Acu\u00F1a": string;
    "Sierra Leona": string;
    Somalia: string;
    Surinam: string;
    "Sud\u00E1n del Sur": string;
    "Santo Tom\u00E9 y Pr\u00EDncipe": string;
    "El Salvador": string;
    Siria: string;
    Suazilandia: string;
    Tailandia: string;
    Tayikistán: string;
    Turkmenistán: string;
    Túnez: string;
    Tonga: string;
    Turquía: string;
    "Trinidad y Tobago": string;
    "Rep\u00FAblica de China": string;
    Tanzania: string;
    Ucrania: string;
    Uganda: string;
    "Caribe Neerland\u00E9s, Ecuador, El Salvador, Estados Unidos, Guam, Hait\u00ED, Islas Marianas del Norte, Islas Marshall, Islas Turcas y Caicos, Islas ultramarinas de Estados Unidos, Islas V\u00EDrgenes Brit\u00E1nicas, Islas V\u00EDrgenes de los Estados Unidos, Micronesia, Palaos, Panam\u00E1, Puerto Rico, Samoa Americana, Territorio Brit\u00E1nico del Oc\u00E9ano \u00CDndico, Timor Oriental": string;
    Uruguay: string;
    Uzbekistán: string;
    Venezuela: string;
    Vietnam: string;
    Vanuatu: string;
    Samoa: string;
    "Camer\u00FAn, Chad, Gab\u00F3n, Guinea Ecuatorial, Rep\u00FAblica Centroafricana, Rep\u00FAblica del Congo": string;
    "Anguila, Antigua y Barbuda, Dominica, Granada, Montserrat, San Crist\u00F3bal y Nieves, San Vicente y las Granadinas, Santa Luc\u00EDa": string;
    "Ben\u00EDn, Burkina Faso, Costa de Marfil, Guinea-Bis\u00E1u, Mal\u00ED, N\u00EDger, Senegal, Togo": string;
    "Nueva Caledonia, Polinesia Francesa, Wallis y Futuna": string;
    Yemen: string;
    "Lesoto, Namibia, Sud\u00E1frica": string;
    Zambia: string;
    Zimbabue: string;
    "Especificar en el campo": string;
};
